@startuml
start
partition prepareRefresh  {
	:设置startupDate;
	:设置Environment;
}
partition obtainFreshBeanFactory  {
	:1.创建DefaultListableBeanFactory;
    :2.loadBeanDefinitions，将BeanDefinitions注册到beanFactory中;
    :3.将beanFactory交由applicationContext管理，也即赋给beanFactory属性。;
}

stop
@enduml